"""add candidate education experience skills

Revision ID: 45f5508b3815
Revises: e3805afe9178
Create Date: 2026-09-18 19:06:23.848568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f5508b3815'
down_revision: Union[str, Sequence[str], None] = 'e3805afe9178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_education_id'), 'candidate_education', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_education_profile_id'), 'candidate_education', ['profile_id'], unique=False)
    op.create_table('candidate_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_experience_id'), 'candidate_experience', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_experience_profile_id'), 'candidate_experience', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_experience_profile_id'), table_name='candidate_experience')
    op.drop_index(op.f('ix_candidate_experience_id'), table_name='candidate_experience')
    op.drop_table('candidate_experience')
    op.drop_index(op.f('ix_candidate_education_profile_id'), table_name='candidate_education')
    op.drop_index(op.f('ix_candidate_education_id'), table_name='candidate_education')
    op.drop_table('candidate_education')
    # ### end Alembic commands ###
