"""add projects and certifications

Revision ID: cb0666ec3a04
Revises: 002175b8e109
Create Date: 2026-09-18 22:04:41.518988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0666ec3a04'
down_revision: Union[str, Sequence[str], None] = '002175b8e109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuing_organization', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('credential_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_certifications_id'), 'candidate_certifications', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_certifications_profile_id'), 'candidate_certifications', ['profile_id'], unique=False)
    op.create_table('candidate_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technologies', sa.Text(), nullable=True),
    sa.Column('project_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_projects_id'), 'candidate_projects', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_projects_profile_id'), 'candidate_projects', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_projects_profile_id'), table_name='candidate_projects')
    op.drop_index(op.f('ix_candidate_projects_id'), table_name='candidate_projects')
    op.drop_table('candidate_projects')
    op.drop_index(op.f('ix_candidate_certifications_profile_id'), table_name='candidate_certifications')
    op.drop_index(op.f('ix_candidate_certifications_id'), table_name='candidate_certifications')
    op.drop_table('candidate_certifications')
    # ### end Alembic commands ###
